### ISSUE TITLE
KILL crashes server in hosted

### ISSUE THREAD

**Issue by timsehn** [dolthub/hosted-issues#92]
In local Dolt, kill works fine.

Start a Dolt sql-server.

Shell 1: Make a long running query.
```
mysql> select sleep(500);
```

Shell 2: Show processlist and kill it
```
mysql> show full processlist;
+------+------+------+------+---------+------+------------------------------------------+-----------------------+
| Id   | User | Host | db   | Command | Time | State                                    | Info                  |
+------+------+------+------+---------+------+------------------------------------------+-----------------------+
|    2 | root | %    | NULL | Query   |    0 | running                                  | show full processlist |
|    3 | root | %    | NULL | Query   |    3 | 
 (0/1 partitions)
 └─ 0 (0/? rows)
     | select sleep(500)     |
+------+------+------+------+---------+------+------------------------------------------+-----------------------+
2 rows in set (0.00 sec)

mysql> kill 3;
Query OK, 0 rows affected (0.01 sec)
```

Shell 1: Killed and killed connection.
```
mysql> select sleep(500);
ERROR 2013 (HY000): Lost connection to MySQL server during query
No connection. Trying to reconnect...
Connection id:    5
Current database: *** NONE ***
```

Shell 3: sql-server logs:
```
2023-04-27T15:27:54-07:00 INFO [no conn] kill query: pid 12 {}
2023-04-27T15:27:54-07:00 WARN [conn 3] error running query {connectTime=2023-04-27T15:27:02-07:00, connectionDb=, error=context canceled, query=select sleep(500)}
2023-04-27T15:27:54-07:00 ERROR [no conn] Conn 3: Flush() failed: set unix /tmp/mysql.sock: use of closed network connection {}
2023-04-27T15:27:54-07:00 INFO [conn 3] ConnectionClosed {}
2023-04-27T15:27:54-07:00 INFO [conn 5] NewConnection {DisableClientMultiStatements=false}
```

Looks fine.

On hosted. Connect three shells to a hosted instance. Follow the same process. All three connections are killed and nothing shows up in the logs. Server also looks like it shuts off from. the CPU and memory profile:

<img width="606" alt="image" src="https://user-images.githubusercontent.com/5376236/235007101-91f11fd5-f1c2-47d4-8292-46b4c6822f14.png">

**Comment by reltuk** [comment]
Fixed in https://github.com/dolthub/vitess/pull/234.

The stack trace looked like:

```
May 03 20:14:08 ip-172-31-11-240 dolt[1350]: goroutine 4746 [running]:
May 03 20:14:08 ip-172-31-11-240 dolt[1350]: github.com/dolthub/vitess/go/netutil.ConnWithTimeouts.SetWriteDeadline(...)
May 03 20:14:08 ip-172-31-11-240 dolt[1350]:         /go/pkg/mod/github.com/dolthub/vitess@v0.0.0-20230407173322-ae1622f38e94/go/netutil/conn.go:71
May 03 20:14:08 ip-172-31-11-240 dolt[1350]: crypto/tls.(*Conn).SetWriteDeadline(...)
May 03 20:14:08 ip-172-31-11-240 dolt[1350]:         /usr/local/go/src/crypto/tls/conn.go:152
May 03 20:14:08 ip-172-31-11-240 dolt[1350]: crypto/tls.(*Conn).closeNotify(0xc00392a380)
May 03 20:14:08 ip-172-31-11-240 dolt[1350]:         /usr/local/go/src/crypto/tls/conn.go:1399 +0xdb
May 03 20:14:08 ip-172-31-11-240 dolt[1350]: crypto/tls.(*Conn).Close(0xc00386cdb0?)
May 03 20:14:08 ip-172-31-11-240 dolt[1350]:         /usr/local/go/src/crypto/tls/conn.go:1369 +0x69
May 03 20:14:08 ip-172-31-11-240 dolt[1350]: github.com/dolthub/vitess/go/mysql.(*Conn).Close(0x1d5adc0?)
May 03 20:14:08 ip-172-31-11-240 dolt[1350]:         /go/pkg/mod/github.com/dolthub/vitess@v0.0.0-20230407173322-ae1622f38e94/go/mysql/conn.go:655 +0x38
May 03 20:14:08 ip-172-31-11-240 dolt[1350]: github.com/dolthub/go-mysql-server/server.(*SessionManager).KillConnection(0xc00386cdb0?, 0x3919968?)
May 03 20:14:08 ip-172-31-11-240 dolt[1350]:         /go/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20230417164611-487575e332ac/server/context.go:243 +0xb1
May 03 20:14:08 ip-172-31-11-240 dolt[1350]: github.com/dolthub/go-mysql-server/sql.(*Context).KillConnection(...)
May 03 20:14:08 ip-172-31-11-240 dolt[1350]:         /go/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20230417164611-487575e332ac/sql/session.go:428
May 03 20:14:08 ip-172-31-11-240 dolt[1350]: github.com/dolthub/dolt/go/libraries/doltcore/sqle/dprocedures.doDoltGC.func1()
May 03 20:14:08 ip-172-31-11-240 dolt[1350]:         /src/libraries/doltcore/sqle/dprocedures/dolt_gc.go:100 +0x264
May 03 20:14:08 ip-172-31-11-240 dolt[1350]: github.com/dolthub/dolt/go/store/types.(*ValueStore).gcProcessRefs(0xc0005c0420, {0x245cff8, 0xc02c04cc80}, 0x1847440?, 0xc02bee1ca0, 0xc025639740, 0xc02befbba8, 0xc02c07e3e0, 0x>
May 03 20:14:08 ip-172-31-11-240 dolt[1350]:         /src/store/types/value_store.go:792 +0x510
May 03 20:14:08 ip-172-31-11-240 dolt[1350]: github.com/dolthub/dolt/go/store/types.(*ValueStore).gc.func3()
May 03 20:14:08 ip-172-31-11-240 dolt[1350]:         /src/store/types/value_store.go:678 +0x95
May 03 20:14:08 ip-172-31-11-240 dolt[1350]: golang.org/x/sync/errgroup.(*Group).Go.func1()
May 03 20:14:08 ip-172-31-11-240 dolt[1350]:         /go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x64
May 03 20:14:08 ip-172-31-11-240 dolt[1350]: created by golang.org/x/sync/errgroup.(*Group).Go
May 03 20:14:08 ip-172-31-11-240 dolt[1350]:         /go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0xa5
```

for example.
